name: Trigger Playwright Tests 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  trigger-pipeline-e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Playwright Tests
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/FranciscoGabriel1/github-search-automation/dispatches \
            -d '{"event_type":"playwright-tests"}'

    
